import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AppSidebar } from "@/src/components/app-sidebar";
import Header from "@/src/components/Header";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/src/components/ui/sidebar";
import { TMDBProvider } from "@/src/providers/tmdb-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const apiKey = process.env.TMDB_API_KEY!;

  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TMDBProvider apiKey={apiKey}>
          <SidebarProvider defaultOpen={false}>
            <AppSidebar />
            <div className="flex-1 flex flex-col w-full">
              {/* Header with Search and Sidebar Trigger */}
              <Header />

              {/* Page Content */}
              <main className="flex-1">{children}</main>
            </div>
          </SidebarProvider>
        </TMDBProvider>
      </body>
    </html>
  );
}
